import Foundation

/// A scalable, JSON-backed catalog of real cities. The single source of truth
/// for both origins and destinations — every city is eligible for both. Journeys
/// are generated by coordinate-based nearest-neighbour lookup, so adding cities
/// is a JSON edit only (no Swift changes).
enum WorldCityCatalog {

    /// All countries (alphabetical), loaded once from the bundled JSON.
    static let countries: [WorldCountry] = loadCountries()

    /// All cities flattened with their country.
    static let allCities: [CityEntry] = countries.flatMap { country in
        country.cities.map {
            CityEntry(city: $0, country: country.country,
                      countryCode: country.countryCode ?? String(country.country.prefix(2)).uppercased())
        }
    }

    // MARK: - Search

    /// Search by city name, country name, or city code (case-insensitive).
    static func search(_ query: String, limit: Int = 80) -> [CityEntry] {
        let q = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !q.isEmpty else { return [] }
        let matches = allCities.filter {
            $0.city.name.lowercased().contains(q)
                || $0.country.lowercased().contains(q)
                || $0.city.code.lowercased().contains(q)
        }
        let prefix = matches.filter { $0.city.name.lowercased().hasPrefix(q) }
        let others = matches.filter { !$0.city.name.lowercased().hasPrefix(q) }
        return Array((prefix + others).prefix(limit))
    }

    // MARK: - Nearest-neighbour

    /// All cities sorted by distance from `coordinate`, excluding anything within
    /// `excludingOriginWithinKm` (so the origin itself never appears). Each pair
    /// is `(city, distanceKm)`.
    static func sortedByDistance(from coordinate: GeoCoordinate,
                                 excludingOriginWithinKm: Double = 5) -> [(entry: CityEntry, km: Double)] {
        allCities
            .map { (entry: $0, km: GeoMath.distanceKm(from: coordinate, to: $0.city.coordinate)) }
            .filter { $0.km >= excludingOriginWithinKm }
            .sorted { lhs, rhs in
                if lhs.km != rhs.km { return lhs.km < rhs.km }
                return (lhs.entry.city.population ?? 0) > (rhs.entry.city.population ?? 0)
            }
    }

    /// The single nearest known city to `coordinate`. Used as a display fallback
    /// when reverse geocoding yields no city name (common in the Simulator or
    /// offline) so the UI shows a real city + code (e.g. "San Francisco" / "SFO")
    /// instead of a generic "Current Location". Coordinate-based, so it's correct
    /// anywhere on Earth and never hardcodes a city.
    static func nearestCity(to coordinate: GeoCoordinate) -> CityEntry? {
        sortedByDistance(from: coordinate, excludingOriginWithinKm: 0).first?.entry
    }

    /// Real cities within a distance band, nearest first.
    static func nearestCities(to coordinate: GeoCoordinate,
                              excludingOriginWithinKm: Double = 5,
                              minDistanceKm: Double, maxDistanceKm: Double,
                              limit: Int) -> [CityEntry] {
        sortedByDistance(from: coordinate, excludingOriginWithinKm: max(excludingOriginWithinKm, minDistanceKm))
            .filter { $0.km <= maxDistanceKm }
            .prefix(limit)
            .map { $0.entry }
    }

    // MARK: - Loading

    private static func loadCountries() -> [WorldCountry] {
        guard let url = Bundle.main.url(forResource: "WorldCities", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([WorldCountry].self, from: data),
              !decoded.isEmpty else {
            return fallback
        }
        return decoded.sorted { $0.country < $1.country }
    }

    /// Minimal embedded fallback if the JSON ever fails to load, so the picker
    /// and journey engine always have real cities to work with.
    private static let fallback: [WorldCountry] = {
        Dictionary(grouping: OriginPresets.all, by: { $0.country })
            .map { country, origins in
                WorldCountry(country: country,
                             countryCode: String(country.prefix(2)).uppercased(),
                             cities: origins.map {
                                 WorldCity(name: $0.city, code: $0.code,
                                           latitude: $0.coordinate.latitude,
                                           longitude: $0.coordinate.longitude)
                             })
            }
            .sorted { $0.country < $1.country }
    }()
}
